<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="source" nsURI="ecore://nasdanika.org/models/source" nsPrefix="org.nasdanika.models.source">
  <eClassifiers xsi:type="ecore:EClass" name="TokenSource" instanceTypeName="java.util.function.Function&lt;String, String>"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comparable" instanceClassName="java.lang.Comparable"
      abstract="true" interface="true">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Position">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eGenericSuperTypes eClassifier="#//Comparable">
      <eTypeArguments eClassifier="#//Position"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Range" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//Marked">
    <eOperations name="contains" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="range" eType="#//Range"/>
    </eOperations>
    <eOperations name="contains" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="position" eType="#//Position"/>
    </eOperations>
    <eOperations name="overlaps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="range" eType="#//Range"/>
    </eOperations>
    <eOperations name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="source" eType="#//Source"/>
    </eOperations>
    <eOperations name="offset" eType="#//Range">
      <eParameters name="position" eType="#//Position"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="begin" eType="#//Position"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//Position"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GenerationMode">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines how own source and contents are usd by the generate() method"/>
    </eAnnotations>
    <eLiterals name="NONE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Skip this source during generation"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SOURCE" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Use only own source, ingnore contents"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CONTENTS" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Do not use own source, generate from contents"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CONCATENATE" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Concatenate own source with source generated by contents"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MERGE" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Own source (original) is merged with new source generated from contents"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source" eSuperTypes="#//Range">
    <eOperations name="generate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Generates source code"/>
      </eAnnotations>
      <eParameters name="tokenSource" eType="#//TokenSource"/>
      <eParameters name="indent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Source" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="    "/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interpolate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generationMode" eType="#//GenerationMode"
        defaultValueLiteral="MERGE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indentFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" eSuperTypes="#//Source">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
